Feature/favorites page
COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List pull request #34
Opened 2017-04-06 03:54 UTC by MavOmidK

Works, tell me if theres anything I missed or bugs.

2017-04-06 13:44 UTC, aagavin requested changes
Looks good. Can you fix merge conflicts.

2017-04-06 13:44 UTC, aagavin commented on src/providers/add-movies.ts
> +  constructor(public af: AngularFire) {
I'm not sure what this file does??

2017-04-06 16:34 UTC, antonybogun requested changes
1. TSLint gives me these errors:
`[12:24:09]  tslint: ...ect/COMP308-Group2-Favourite-Movie-List/src/pages/movie-details/movie-details.ts, line: 6
[12:24:09]  tslint: ...08-W2017-Project/COMP308-Group2-Favourite-Movie-List/src/providers/add-movies.ts, line: 1
[12:24:09]  tslint: ...08-W2017-Project/COMP308-Group2-Favourite-Movie-List/src/providers/add-movies.ts, line: 2
[12:24:09]  tslint: ...08-W2017-Project/COMP308-Group2-Favourite-Movie-List/src/providers/add-movies.ts, line: 2
            Unused import: 'FirebaseObjectObservable'

       L5:  // import angularfire
       L6:  import { AngularFire, FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2';

            Unused import: 'Component'

       L1:  import { Component } from '@angular/core';
       L2:  import { NavController, NavParams } from 'ionic-angular';

            Unused import: 'NavController'

       L1:  import { Component } from '@angular/core';
       L2:  import { NavController, NavParams } from 'ionic-angular';
       L3:  import {Injectable} from "@angular/core";

            Unused import: 'NavParams'

       L1:  import { Component } from '@angular/core';
       L2:  import { NavController, NavParams } from 'ionic-angular';
       L3:  import {Injectable} from "@angular/core";

[12:24:09]  lint finished in 5.40 s`

2. Can you please update 'Add to favorites' button on 'Movie Details' page to 'Remove from favorites' once clicked. It will give user a chance to make sure that movie was added successfully without going to 'Favorites' page

2017-04-06 16:42 UTC, eddieysong commented
It looks like Omid missed a commit in `dev`, so I tried to resolve the merge conflicts by including new lines from both branches. There doesn't seem to be any deletions, so it should work... hopefully it doesn't mess up other branches..

2017-04-06 17:03 UTC, eddieysong approved these changes
Tested everything in `ionic serve`, functionalities seem to be complete and they play nicely. One exception was thrown by AuthData (auth-data.ts), but I cannot recreate it so it might have just been a firebase thing.

2017-04-07 19:17 UTC, antonybogun approved these changes

2017-04-07 19:20 UTC, aagavin approved these changes

2017-04-07 19:21 UTC, aagavin approved these changes

2017-04-07 19:21 UTC, merged