Feature/search user
COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List pull request #37
Opened 2017-04-06 15:37 UTC by eddieysong

Search user view is now returning a list of users matched by either _email or _displayName. Tested with `ionic serve`.

2017-04-06 15:40 UTC, eddieysong commented
will reopen after deleting some unused imports

2017-04-06 16:45 UTC, antonybogun requested changes
1. Please move user icon to ./src/assets/images/ 

2. Please add 'No results found for <query>' when there is no user with queried display name or email

2017-04-06 19:14 UTC, antonybogun approved these changes

2017-04-07 14:21 UTC, aagavin approved these changes

2017-04-07 14:21 UTC, merged